# cache:
# - "c:\\sr" # stack root, short paths == less problems

build: off

before_test:
- curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-i386
- 7z x stack.zip stack.exe

clone_folder: "c:\\project"
environment:
  global:
    STACK_ROOT: "c:\\sr"

test_script:
- stack init
- stack setup > nul
- echo "" | stack --no-terminal build
- stack exec -- hlint test
- stack exec -- hlint src --no-exit-code
